### PR TITLE
added docker-compose

### PR DESCRIPTION
**Pull request by thebigbone**

### CODE REVIEW

**Review by TheHamkerCat — COMMENTED** [review]
not needed

**Comment by thebigbone** [comment]
docker-compose makes the deployment easier. are you unaware of that fact?

**Comment by TheHamkerCat** [comment]
We should use docker-compose only when there are multiple containers or the configuration options are too many, Dockerfile is enough here.

**Comment by thebigbone** [comment]
Not true. The number of containers has never been the metric to measure when writing a docker-compose file. As I said before, it is meant to deploy without any hassle.

**Comment by TheHamkerCat** [comment]
I don't understand how docker-compose is useful in this small project 

what can we achieve by using `docker-compose up` instead of `docker build . -t tgvc && docker run tgvc` ?

**Comment by thebigbone** [comment]
You should look into the documentation. I cannot explain it any further.

**Comment by rojvv** [comment]
@TheHamkerCat It's not useless either.

**Pull request closed without merging**
